#pragma once

#define RAFT_KVSTORAGE_DEBUG                true
#define RAFT_KVSTORAGE_TIME_FACTOR          10

#define RAFT_KVSTORAGE_HEARTBEAT_SLEEP_TIME 25 * RAFT_KVSTORAGE_TIME_FACTOR
#define RAFT_KVSTORAGE_APPLY_INTERVAL       10 * RAFT_KVSTORAGE_TIME_FACTOR

#define RAFT_KVSTORAGE_MIN_WAIT_TIME_BEFORE_ELECTION    300 * RAFT_KVSTORAGE_TIME_FACTOR
#define RAFT_KVSTORAGE_MAX_WAIT_TIME_BEFORE_ELECTION    500 * RAFT_KVSTORAGE_TIME_FACTOR

#define RAFT_KVSTORAGE_CONSENSUS_TIME       1000 * RAFT_KVSTORAGE_TIME_FACTOR

#define RAFT_KVSTORAGE_COROUTINE_THREAD_NUM 1
#define RAFT_KVSTORAGE_COROUTINE_AS_WORKER  false

#define RAFT_KVSTORAGE_OK                   "OK"
#define RAFT_KVSTORAGE_ERR_NO_KEY           "ErrNoKey"
#define RAFT_KVSTORAGE_TIMEOUT              "Timeout"
#define RAFT_KVSTORAGE_ERR_WRONG_LEADER     "ErrWrongLeader"

