// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raftBase.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_raftBase_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_raftBase_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_raftBase_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_raftBase_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[7]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_raftBase_2eproto;
namespace raft {
class appendEntriesArgs;
class appendEntriesArgsDefaultTypeInternal;
extern appendEntriesArgsDefaultTypeInternal _appendEntriesArgs_default_instance_;
class appendEntriesReply;
class appendEntriesReplyDefaultTypeInternal;
extern appendEntriesReplyDefaultTypeInternal _appendEntriesReply_default_instance_;
class installSnapshotArgs;
class installSnapshotArgsDefaultTypeInternal;
extern installSnapshotArgsDefaultTypeInternal _installSnapshotArgs_default_instance_;
class installSnapshotReply;
class installSnapshotReplyDefaultTypeInternal;
extern installSnapshotReplyDefaultTypeInternal _installSnapshotReply_default_instance_;
class logEntry;
class logEntryDefaultTypeInternal;
extern logEntryDefaultTypeInternal _logEntry_default_instance_;
class requestVoteArgs;
class requestVoteArgsDefaultTypeInternal;
extern requestVoteArgsDefaultTypeInternal _requestVoteArgs_default_instance_;
class requestVoteReply;
class requestVoteReplyDefaultTypeInternal;
extern requestVoteReplyDefaultTypeInternal _requestVoteReply_default_instance_;
}  // namespace raft
PROTOBUF_NAMESPACE_OPEN
template<> ::raft::appendEntriesArgs* Arena::CreateMaybeMessage<::raft::appendEntriesArgs>(Arena*);
template<> ::raft::appendEntriesReply* Arena::CreateMaybeMessage<::raft::appendEntriesReply>(Arena*);
template<> ::raft::installSnapshotArgs* Arena::CreateMaybeMessage<::raft::installSnapshotArgs>(Arena*);
template<> ::raft::installSnapshotReply* Arena::CreateMaybeMessage<::raft::installSnapshotReply>(Arena*);
template<> ::raft::logEntry* Arena::CreateMaybeMessage<::raft::logEntry>(Arena*);
template<> ::raft::requestVoteArgs* Arena::CreateMaybeMessage<::raft::requestVoteArgs>(Arena*);
template<> ::raft::requestVoteReply* Arena::CreateMaybeMessage<::raft::requestVoteReply>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace raft {

enum netState : int {
  DISCONNECTED = 0,
  CONNECTED = 1,
  netState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  netState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool netState_IsValid(int value);
constexpr netState netState_MIN = DISCONNECTED;
constexpr netState netState_MAX = CONNECTED;
constexpr int netState_ARRAYSIZE = netState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* netState_descriptor();
template<typename T>
inline const std::string& netState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, netState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function netState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    netState_descriptor(), enum_t_value);
}
inline bool netState_Parse(
    const std::string& name, netState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<netState>(
    netState_descriptor(), name, value);
}
enum voteState : int {
  KILLED = 0,
  VOTED = 1,
  EXPIRE = 2,
  NORMAL = 3,
  voteState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  voteState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool voteState_IsValid(int value);
constexpr voteState voteState_MIN = KILLED;
constexpr voteState voteState_MAX = NORMAL;
constexpr int voteState_ARRAYSIZE = voteState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* voteState_descriptor();
template<typename T>
inline const std::string& voteState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, voteState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function voteState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    voteState_descriptor(), enum_t_value);
}
inline bool voteState_Parse(
    const std::string& name, voteState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<voteState>(
    voteState_descriptor(), name, value);
}
// ===================================================================

class logEntry PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.logEntry) */ {
 public:
  inline logEntry() : logEntry(nullptr) {};
  virtual ~logEntry();

  logEntry(const logEntry& from);
  logEntry(logEntry&& from) noexcept
    : logEntry() {
    *this = ::std::move(from);
  }

  inline logEntry& operator=(const logEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline logEntry& operator=(logEntry&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const logEntry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const logEntry* internal_default_instance() {
    return reinterpret_cast<const logEntry*>(
               &_logEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(logEntry& a, logEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(logEntry* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(logEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline logEntry* New() const final {
    return CreateMaybeMessage<logEntry>(nullptr);
  }

  logEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<logEntry>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const logEntry& from);
  void MergeFrom(const logEntry& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(logEntry* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.logEntry";
  }
  protected:
  explicit logEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_raftBase_2eproto);
    return ::descriptor_table_raftBase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandFieldNumber = 1,
    kTermFieldNumber = 2,
    kIndexFieldNumber = 3,
  };
  // bytes command = 1;
  void clear_command();
  const std::string& command() const;
  void set_command(const std::string& value);
  void set_command(std::string&& value);
  void set_command(const char* value);
  void set_command(const void* value, size_t size);
  std::string* mutable_command();
  std::string* release_command();
  void set_allocated_command(std::string* command);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_command();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_command(
      std::string* command);
  private:
  const std::string& _internal_command() const;
  void _internal_set_command(const std::string& value);
  std::string* _internal_mutable_command();
  public:

  // int32 term = 2;
  void clear_term();
  ::PROTOBUF_NAMESPACE_ID::int32 term() const;
  void set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_term() const;
  void _internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 index = 3;
  void clear_index();
  ::PROTOBUF_NAMESPACE_ID::int32 index() const;
  void set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_index() const;
  void _internal_set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:raft.logEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_;
  ::PROTOBUF_NAMESPACE_ID::int32 term_;
  ::PROTOBUF_NAMESPACE_ID::int32 index_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_raftBase_2eproto;
};
// -------------------------------------------------------------------

class appendEntriesArgs PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.appendEntriesArgs) */ {
 public:
  inline appendEntriesArgs() : appendEntriesArgs(nullptr) {};
  virtual ~appendEntriesArgs();

  appendEntriesArgs(const appendEntriesArgs& from);
  appendEntriesArgs(appendEntriesArgs&& from) noexcept
    : appendEntriesArgs() {
    *this = ::std::move(from);
  }

  inline appendEntriesArgs& operator=(const appendEntriesArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline appendEntriesArgs& operator=(appendEntriesArgs&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const appendEntriesArgs& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const appendEntriesArgs* internal_default_instance() {
    return reinterpret_cast<const appendEntriesArgs*>(
               &_appendEntriesArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(appendEntriesArgs& a, appendEntriesArgs& b) {
    a.Swap(&b);
  }
  inline void Swap(appendEntriesArgs* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(appendEntriesArgs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline appendEntriesArgs* New() const final {
    return CreateMaybeMessage<appendEntriesArgs>(nullptr);
  }

  appendEntriesArgs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<appendEntriesArgs>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const appendEntriesArgs& from);
  void MergeFrom(const appendEntriesArgs& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(appendEntriesArgs* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.appendEntriesArgs";
  }
  protected:
  explicit appendEntriesArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_raftBase_2eproto);
    return ::descriptor_table_raftBase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntriesFieldNumber = 5,
    kTermFieldNumber = 1,
    kLeaderIdFieldNumber = 2,
    kPrevLogIndexFieldNumber = 3,
    kPrevLogTermFieldNumber = 4,
    kLeaderCommitFieldNumber = 6,
  };
  // repeated .raft.logEntry entries = 5;
  int entries_size() const;
  private:
  int _internal_entries_size() const;
  public:
  void clear_entries();
  ::raft::logEntry* mutable_entries(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raft::logEntry >*
      mutable_entries();
  private:
  const ::raft::logEntry& _internal_entries(int index) const;
  ::raft::logEntry* _internal_add_entries();
  public:
  const ::raft::logEntry& entries(int index) const;
  ::raft::logEntry* add_entries();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raft::logEntry >&
      entries() const;

  // int32 term = 1;
  void clear_term();
  ::PROTOBUF_NAMESPACE_ID::int32 term() const;
  void set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_term() const;
  void _internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 leader_id = 2;
  void clear_leader_id();
  ::PROTOBUF_NAMESPACE_ID::int32 leader_id() const;
  void set_leader_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_leader_id() const;
  void _internal_set_leader_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 prev_log_index = 3;
  void clear_prev_log_index();
  ::PROTOBUF_NAMESPACE_ID::int32 prev_log_index() const;
  void set_prev_log_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_prev_log_index() const;
  void _internal_set_prev_log_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 prev_log_term = 4;
  void clear_prev_log_term();
  ::PROTOBUF_NAMESPACE_ID::int32 prev_log_term() const;
  void set_prev_log_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_prev_log_term() const;
  void _internal_set_prev_log_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 leader_commit = 6;
  void clear_leader_commit();
  ::PROTOBUF_NAMESPACE_ID::int32 leader_commit() const;
  void set_leader_commit(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_leader_commit() const;
  void _internal_set_leader_commit(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:raft.appendEntriesArgs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raft::logEntry > entries_;
  ::PROTOBUF_NAMESPACE_ID::int32 term_;
  ::PROTOBUF_NAMESPACE_ID::int32 leader_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 prev_log_index_;
  ::PROTOBUF_NAMESPACE_ID::int32 prev_log_term_;
  ::PROTOBUF_NAMESPACE_ID::int32 leader_commit_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_raftBase_2eproto;
};
// -------------------------------------------------------------------

class appendEntriesReply PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.appendEntriesReply) */ {
 public:
  inline appendEntriesReply() : appendEntriesReply(nullptr) {};
  virtual ~appendEntriesReply();

  appendEntriesReply(const appendEntriesReply& from);
  appendEntriesReply(appendEntriesReply&& from) noexcept
    : appendEntriesReply() {
    *this = ::std::move(from);
  }

  inline appendEntriesReply& operator=(const appendEntriesReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline appendEntriesReply& operator=(appendEntriesReply&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const appendEntriesReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const appendEntriesReply* internal_default_instance() {
    return reinterpret_cast<const appendEntriesReply*>(
               &_appendEntriesReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(appendEntriesReply& a, appendEntriesReply& b) {
    a.Swap(&b);
  }
  inline void Swap(appendEntriesReply* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(appendEntriesReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline appendEntriesReply* New() const final {
    return CreateMaybeMessage<appendEntriesReply>(nullptr);
  }

  appendEntriesReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<appendEntriesReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const appendEntriesReply& from);
  void MergeFrom(const appendEntriesReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(appendEntriesReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.appendEntriesReply";
  }
  protected:
  explicit appendEntriesReply(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_raftBase_2eproto);
    return ::descriptor_table_raftBase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kSuccessFieldNumber = 2,
    kUpdateNextIndexFieldNumber = 3,
    kStateFieldNumber = 4,
  };
  // int32 term = 1;
  void clear_term();
  ::PROTOBUF_NAMESPACE_ID::int32 term() const;
  void set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_term() const;
  void _internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 update_next_index = 3;
  void clear_update_next_index();
  ::PROTOBUF_NAMESPACE_ID::int32 update_next_index() const;
  void set_update_next_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_update_next_index() const;
  void _internal_set_update_next_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .raft.netState state = 4;
  void clear_state();
  ::raft::netState state() const;
  void set_state(::raft::netState value);
  private:
  ::raft::netState _internal_state() const;
  void _internal_set_state(::raft::netState value);
  public:

  // @@protoc_insertion_point(class_scope:raft.appendEntriesReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 term_;
  bool success_;
  ::PROTOBUF_NAMESPACE_ID::int32 update_next_index_;
  int state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_raftBase_2eproto;
};
// -------------------------------------------------------------------

class requestVoteArgs PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.requestVoteArgs) */ {
 public:
  inline requestVoteArgs() : requestVoteArgs(nullptr) {};
  virtual ~requestVoteArgs();

  requestVoteArgs(const requestVoteArgs& from);
  requestVoteArgs(requestVoteArgs&& from) noexcept
    : requestVoteArgs() {
    *this = ::std::move(from);
  }

  inline requestVoteArgs& operator=(const requestVoteArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline requestVoteArgs& operator=(requestVoteArgs&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const requestVoteArgs& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const requestVoteArgs* internal_default_instance() {
    return reinterpret_cast<const requestVoteArgs*>(
               &_requestVoteArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(requestVoteArgs& a, requestVoteArgs& b) {
    a.Swap(&b);
  }
  inline void Swap(requestVoteArgs* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(requestVoteArgs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline requestVoteArgs* New() const final {
    return CreateMaybeMessage<requestVoteArgs>(nullptr);
  }

  requestVoteArgs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<requestVoteArgs>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const requestVoteArgs& from);
  void MergeFrom(const requestVoteArgs& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(requestVoteArgs* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.requestVoteArgs";
  }
  protected:
  explicit requestVoteArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_raftBase_2eproto);
    return ::descriptor_table_raftBase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kCandidateIdFieldNumber = 2,
    kLastLogIndexFieldNumber = 3,
    kLastLogTermFieldNumber = 4,
  };
  // int32 term = 1;
  void clear_term();
  ::PROTOBUF_NAMESPACE_ID::int32 term() const;
  void set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_term() const;
  void _internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 candidate_id = 2;
  void clear_candidate_id();
  ::PROTOBUF_NAMESPACE_ID::int32 candidate_id() const;
  void set_candidate_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_candidate_id() const;
  void _internal_set_candidate_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 last_log_index = 3;
  void clear_last_log_index();
  ::PROTOBUF_NAMESPACE_ID::int32 last_log_index() const;
  void set_last_log_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_last_log_index() const;
  void _internal_set_last_log_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 last_log_term = 4;
  void clear_last_log_term();
  ::PROTOBUF_NAMESPACE_ID::int32 last_log_term() const;
  void set_last_log_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_last_log_term() const;
  void _internal_set_last_log_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:raft.requestVoteArgs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 term_;
  ::PROTOBUF_NAMESPACE_ID::int32 candidate_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 last_log_index_;
  ::PROTOBUF_NAMESPACE_ID::int32 last_log_term_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_raftBase_2eproto;
};
// -------------------------------------------------------------------

class requestVoteReply PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.requestVoteReply) */ {
 public:
  inline requestVoteReply() : requestVoteReply(nullptr) {};
  virtual ~requestVoteReply();

  requestVoteReply(const requestVoteReply& from);
  requestVoteReply(requestVoteReply&& from) noexcept
    : requestVoteReply() {
    *this = ::std::move(from);
  }

  inline requestVoteReply& operator=(const requestVoteReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline requestVoteReply& operator=(requestVoteReply&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const requestVoteReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const requestVoteReply* internal_default_instance() {
    return reinterpret_cast<const requestVoteReply*>(
               &_requestVoteReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(requestVoteReply& a, requestVoteReply& b) {
    a.Swap(&b);
  }
  inline void Swap(requestVoteReply* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(requestVoteReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline requestVoteReply* New() const final {
    return CreateMaybeMessage<requestVoteReply>(nullptr);
  }

  requestVoteReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<requestVoteReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const requestVoteReply& from);
  void MergeFrom(const requestVoteReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(requestVoteReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.requestVoteReply";
  }
  protected:
  explicit requestVoteReply(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_raftBase_2eproto);
    return ::descriptor_table_raftBase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kVoteGrantedFieldNumber = 2,
    kStateFieldNumber = 3,
  };
  // int32 term = 1;
  void clear_term();
  ::PROTOBUF_NAMESPACE_ID::int32 term() const;
  void set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_term() const;
  void _internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool vote_granted = 2;
  void clear_vote_granted();
  bool vote_granted() const;
  void set_vote_granted(bool value);
  private:
  bool _internal_vote_granted() const;
  void _internal_set_vote_granted(bool value);
  public:

  // .raft.voteState state = 3;
  void clear_state();
  ::raft::voteState state() const;
  void set_state(::raft::voteState value);
  private:
  ::raft::voteState _internal_state() const;
  void _internal_set_state(::raft::voteState value);
  public:

  // @@protoc_insertion_point(class_scope:raft.requestVoteReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 term_;
  bool vote_granted_;
  int state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_raftBase_2eproto;
};
// -------------------------------------------------------------------

class installSnapshotArgs PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.installSnapshotArgs) */ {
 public:
  inline installSnapshotArgs() : installSnapshotArgs(nullptr) {};
  virtual ~installSnapshotArgs();

  installSnapshotArgs(const installSnapshotArgs& from);
  installSnapshotArgs(installSnapshotArgs&& from) noexcept
    : installSnapshotArgs() {
    *this = ::std::move(from);
  }

  inline installSnapshotArgs& operator=(const installSnapshotArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline installSnapshotArgs& operator=(installSnapshotArgs&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const installSnapshotArgs& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const installSnapshotArgs* internal_default_instance() {
    return reinterpret_cast<const installSnapshotArgs*>(
               &_installSnapshotArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(installSnapshotArgs& a, installSnapshotArgs& b) {
    a.Swap(&b);
  }
  inline void Swap(installSnapshotArgs* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(installSnapshotArgs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline installSnapshotArgs* New() const final {
    return CreateMaybeMessage<installSnapshotArgs>(nullptr);
  }

  installSnapshotArgs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<installSnapshotArgs>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const installSnapshotArgs& from);
  void MergeFrom(const installSnapshotArgs& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(installSnapshotArgs* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.installSnapshotArgs";
  }
  protected:
  explicit installSnapshotArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_raftBase_2eproto);
    return ::descriptor_table_raftBase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 5,
    kLeaderIdFieldNumber = 1,
    kTermFieldNumber = 2,
    kLastIndexFieldNumber = 3,
    kLastTermFieldNumber = 4,
  };
  // bytes data = 5;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_data(
      std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int32 leader_id = 1;
  void clear_leader_id();
  ::PROTOBUF_NAMESPACE_ID::int32 leader_id() const;
  void set_leader_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_leader_id() const;
  void _internal_set_leader_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 term = 2;
  void clear_term();
  ::PROTOBUF_NAMESPACE_ID::int32 term() const;
  void set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_term() const;
  void _internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 last_index = 3;
  void clear_last_index();
  ::PROTOBUF_NAMESPACE_ID::int32 last_index() const;
  void set_last_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_last_index() const;
  void _internal_set_last_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 last_term = 4;
  void clear_last_term();
  ::PROTOBUF_NAMESPACE_ID::int32 last_term() const;
  void set_last_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_last_term() const;
  void _internal_set_last_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:raft.installSnapshotArgs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::PROTOBUF_NAMESPACE_ID::int32 leader_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 term_;
  ::PROTOBUF_NAMESPACE_ID::int32 last_index_;
  ::PROTOBUF_NAMESPACE_ID::int32 last_term_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_raftBase_2eproto;
};
// -------------------------------------------------------------------

class installSnapshotReply PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.installSnapshotReply) */ {
 public:
  inline installSnapshotReply() : installSnapshotReply(nullptr) {};
  virtual ~installSnapshotReply();

  installSnapshotReply(const installSnapshotReply& from);
  installSnapshotReply(installSnapshotReply&& from) noexcept
    : installSnapshotReply() {
    *this = ::std::move(from);
  }

  inline installSnapshotReply& operator=(const installSnapshotReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline installSnapshotReply& operator=(installSnapshotReply&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const installSnapshotReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const installSnapshotReply* internal_default_instance() {
    return reinterpret_cast<const installSnapshotReply*>(
               &_installSnapshotReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(installSnapshotReply& a, installSnapshotReply& b) {
    a.Swap(&b);
  }
  inline void Swap(installSnapshotReply* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(installSnapshotReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline installSnapshotReply* New() const final {
    return CreateMaybeMessage<installSnapshotReply>(nullptr);
  }

  installSnapshotReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<installSnapshotReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const installSnapshotReply& from);
  void MergeFrom(const installSnapshotReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(installSnapshotReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.installSnapshotReply";
  }
  protected:
  explicit installSnapshotReply(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_raftBase_2eproto);
    return ::descriptor_table_raftBase_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
  };
  // int32 term = 1;
  void clear_term();
  ::PROTOBUF_NAMESPACE_ID::int32 term() const;
  void set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_term() const;
  void _internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:raft.installSnapshotReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 term_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_raftBase_2eproto;
};
// ===================================================================

class raftBase_Stub;

class raftBase : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline raftBase() {};
 public:
  virtual ~raftBase();

  typedef raftBase_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void appendEntries(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raft::appendEntriesArgs* request,
                       ::raft::appendEntriesReply* response,
                       ::google::protobuf::Closure* done);
  virtual void installSnapshot(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raft::installSnapshotArgs* request,
                       ::raft::installSnapshotReply* response,
                       ::google::protobuf::Closure* done);
  virtual void requestVote(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raft::requestVoteArgs* request,
                       ::raft::requestVoteReply* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(raftBase);
};

class raftBase_Stub : public raftBase {
 public:
  raftBase_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  raftBase_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~raftBase_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements raftBase ------------------------------------------

  void appendEntries(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raft::appendEntriesArgs* request,
                       ::raft::appendEntriesReply* response,
                       ::google::protobuf::Closure* done);
  void installSnapshot(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raft::installSnapshotArgs* request,
                       ::raft::installSnapshotReply* response,
                       ::google::protobuf::Closure* done);
  void requestVote(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raft::requestVoteArgs* request,
                       ::raft::requestVoteReply* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(raftBase_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// logEntry

// bytes command = 1;
inline void logEntry::clear_command() {
  command_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& logEntry::command() const {
  // @@protoc_insertion_point(field_get:raft.logEntry.command)
  return _internal_command();
}
inline void logEntry::set_command(const std::string& value) {
  _internal_set_command(value);
  // @@protoc_insertion_point(field_set:raft.logEntry.command)
}
inline std::string* logEntry::mutable_command() {
  // @@protoc_insertion_point(field_mutable:raft.logEntry.command)
  return _internal_mutable_command();
}
inline const std::string& logEntry::_internal_command() const {
  return command_.Get();
}
inline void logEntry::_internal_set_command(const std::string& value) {
  
  command_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void logEntry::set_command(std::string&& value) {
  
  command_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:raft.logEntry.command)
}
inline void logEntry::set_command(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  command_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:raft.logEntry.command)
}
inline void logEntry::set_command(const void* value,
    size_t size) {
  
  command_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:raft.logEntry.command)
}
inline std::string* logEntry::_internal_mutable_command() {
  
  return command_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* logEntry::release_command() {
  // @@protoc_insertion_point(field_release:raft.logEntry.command)
  return command_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void logEntry::set_allocated_command(std::string* command) {
  if (command != nullptr) {
    
  } else {
    
  }
  command_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), command,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:raft.logEntry.command)
}
inline std::string* logEntry::unsafe_arena_release_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:raft.logEntry.command)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return command_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void logEntry::unsafe_arena_set_allocated_command(
    std::string* command) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (command != nullptr) {
    
  } else {
    
  }
  command_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      command, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:raft.logEntry.command)
}

// int32 term = 2;
inline void logEntry::clear_term() {
  term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 logEntry::_internal_term() const {
  return term_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 logEntry::term() const {
  // @@protoc_insertion_point(field_get:raft.logEntry.term)
  return _internal_term();
}
inline void logEntry::_internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  term_ = value;
}
inline void logEntry::set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.logEntry.term)
}

// int32 index = 3;
inline void logEntry::clear_index() {
  index_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 logEntry::_internal_index() const {
  return index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 logEntry::index() const {
  // @@protoc_insertion_point(field_get:raft.logEntry.index)
  return _internal_index();
}
inline void logEntry::_internal_set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  index_ = value;
}
inline void logEntry::set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:raft.logEntry.index)
}

// -------------------------------------------------------------------

// appendEntriesArgs

// int32 term = 1;
inline void appendEntriesArgs::clear_term() {
  term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesArgs::_internal_term() const {
  return term_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesArgs::term() const {
  // @@protoc_insertion_point(field_get:raft.appendEntriesArgs.term)
  return _internal_term();
}
inline void appendEntriesArgs::_internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  term_ = value;
}
inline void appendEntriesArgs::set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.appendEntriesArgs.term)
}

// int32 leader_id = 2;
inline void appendEntriesArgs::clear_leader_id() {
  leader_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesArgs::_internal_leader_id() const {
  return leader_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesArgs::leader_id() const {
  // @@protoc_insertion_point(field_get:raft.appendEntriesArgs.leader_id)
  return _internal_leader_id();
}
inline void appendEntriesArgs::_internal_set_leader_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  leader_id_ = value;
}
inline void appendEntriesArgs::set_leader_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_leader_id(value);
  // @@protoc_insertion_point(field_set:raft.appendEntriesArgs.leader_id)
}

// int32 prev_log_index = 3;
inline void appendEntriesArgs::clear_prev_log_index() {
  prev_log_index_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesArgs::_internal_prev_log_index() const {
  return prev_log_index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesArgs::prev_log_index() const {
  // @@protoc_insertion_point(field_get:raft.appendEntriesArgs.prev_log_index)
  return _internal_prev_log_index();
}
inline void appendEntriesArgs::_internal_set_prev_log_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  prev_log_index_ = value;
}
inline void appendEntriesArgs::set_prev_log_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_prev_log_index(value);
  // @@protoc_insertion_point(field_set:raft.appendEntriesArgs.prev_log_index)
}

// int32 prev_log_term = 4;
inline void appendEntriesArgs::clear_prev_log_term() {
  prev_log_term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesArgs::_internal_prev_log_term() const {
  return prev_log_term_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesArgs::prev_log_term() const {
  // @@protoc_insertion_point(field_get:raft.appendEntriesArgs.prev_log_term)
  return _internal_prev_log_term();
}
inline void appendEntriesArgs::_internal_set_prev_log_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  prev_log_term_ = value;
}
inline void appendEntriesArgs::set_prev_log_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_prev_log_term(value);
  // @@protoc_insertion_point(field_set:raft.appendEntriesArgs.prev_log_term)
}

// repeated .raft.logEntry entries = 5;
inline int appendEntriesArgs::_internal_entries_size() const {
  return entries_.size();
}
inline int appendEntriesArgs::entries_size() const {
  return _internal_entries_size();
}
inline void appendEntriesArgs::clear_entries() {
  entries_.Clear();
}
inline ::raft::logEntry* appendEntriesArgs::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:raft.appendEntriesArgs.entries)
  return entries_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raft::logEntry >*
appendEntriesArgs::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:raft.appendEntriesArgs.entries)
  return &entries_;
}
inline const ::raft::logEntry& appendEntriesArgs::_internal_entries(int index) const {
  return entries_.Get(index);
}
inline const ::raft::logEntry& appendEntriesArgs::entries(int index) const {
  // @@protoc_insertion_point(field_get:raft.appendEntriesArgs.entries)
  return _internal_entries(index);
}
inline ::raft::logEntry* appendEntriesArgs::_internal_add_entries() {
  return entries_.Add();
}
inline ::raft::logEntry* appendEntriesArgs::add_entries() {
  // @@protoc_insertion_point(field_add:raft.appendEntriesArgs.entries)
  return _internal_add_entries();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raft::logEntry >&
appendEntriesArgs::entries() const {
  // @@protoc_insertion_point(field_list:raft.appendEntriesArgs.entries)
  return entries_;
}

// int32 leader_commit = 6;
inline void appendEntriesArgs::clear_leader_commit() {
  leader_commit_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesArgs::_internal_leader_commit() const {
  return leader_commit_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesArgs::leader_commit() const {
  // @@protoc_insertion_point(field_get:raft.appendEntriesArgs.leader_commit)
  return _internal_leader_commit();
}
inline void appendEntriesArgs::_internal_set_leader_commit(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  leader_commit_ = value;
}
inline void appendEntriesArgs::set_leader_commit(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_leader_commit(value);
  // @@protoc_insertion_point(field_set:raft.appendEntriesArgs.leader_commit)
}

// -------------------------------------------------------------------

// appendEntriesReply

// int32 term = 1;
inline void appendEntriesReply::clear_term() {
  term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesReply::_internal_term() const {
  return term_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesReply::term() const {
  // @@protoc_insertion_point(field_get:raft.appendEntriesReply.term)
  return _internal_term();
}
inline void appendEntriesReply::_internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  term_ = value;
}
inline void appendEntriesReply::set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.appendEntriesReply.term)
}

// bool success = 2;
inline void appendEntriesReply::clear_success() {
  success_ = false;
}
inline bool appendEntriesReply::_internal_success() const {
  return success_;
}
inline bool appendEntriesReply::success() const {
  // @@protoc_insertion_point(field_get:raft.appendEntriesReply.success)
  return _internal_success();
}
inline void appendEntriesReply::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void appendEntriesReply::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:raft.appendEntriesReply.success)
}

// int32 update_next_index = 3;
inline void appendEntriesReply::clear_update_next_index() {
  update_next_index_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesReply::_internal_update_next_index() const {
  return update_next_index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 appendEntriesReply::update_next_index() const {
  // @@protoc_insertion_point(field_get:raft.appendEntriesReply.update_next_index)
  return _internal_update_next_index();
}
inline void appendEntriesReply::_internal_set_update_next_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  update_next_index_ = value;
}
inline void appendEntriesReply::set_update_next_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_update_next_index(value);
  // @@protoc_insertion_point(field_set:raft.appendEntriesReply.update_next_index)
}

// .raft.netState state = 4;
inline void appendEntriesReply::clear_state() {
  state_ = 0;
}
inline ::raft::netState appendEntriesReply::_internal_state() const {
  return static_cast< ::raft::netState >(state_);
}
inline ::raft::netState appendEntriesReply::state() const {
  // @@protoc_insertion_point(field_get:raft.appendEntriesReply.state)
  return _internal_state();
}
inline void appendEntriesReply::_internal_set_state(::raft::netState value) {
  
  state_ = value;
}
inline void appendEntriesReply::set_state(::raft::netState value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:raft.appendEntriesReply.state)
}

// -------------------------------------------------------------------

// requestVoteArgs

// int32 term = 1;
inline void requestVoteArgs::clear_term() {
  term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 requestVoteArgs::_internal_term() const {
  return term_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 requestVoteArgs::term() const {
  // @@protoc_insertion_point(field_get:raft.requestVoteArgs.term)
  return _internal_term();
}
inline void requestVoteArgs::_internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  term_ = value;
}
inline void requestVoteArgs::set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.requestVoteArgs.term)
}

// int32 candidate_id = 2;
inline void requestVoteArgs::clear_candidate_id() {
  candidate_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 requestVoteArgs::_internal_candidate_id() const {
  return candidate_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 requestVoteArgs::candidate_id() const {
  // @@protoc_insertion_point(field_get:raft.requestVoteArgs.candidate_id)
  return _internal_candidate_id();
}
inline void requestVoteArgs::_internal_set_candidate_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  candidate_id_ = value;
}
inline void requestVoteArgs::set_candidate_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_candidate_id(value);
  // @@protoc_insertion_point(field_set:raft.requestVoteArgs.candidate_id)
}

// int32 last_log_index = 3;
inline void requestVoteArgs::clear_last_log_index() {
  last_log_index_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 requestVoteArgs::_internal_last_log_index() const {
  return last_log_index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 requestVoteArgs::last_log_index() const {
  // @@protoc_insertion_point(field_get:raft.requestVoteArgs.last_log_index)
  return _internal_last_log_index();
}
inline void requestVoteArgs::_internal_set_last_log_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  last_log_index_ = value;
}
inline void requestVoteArgs::set_last_log_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_last_log_index(value);
  // @@protoc_insertion_point(field_set:raft.requestVoteArgs.last_log_index)
}

// int32 last_log_term = 4;
inline void requestVoteArgs::clear_last_log_term() {
  last_log_term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 requestVoteArgs::_internal_last_log_term() const {
  return last_log_term_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 requestVoteArgs::last_log_term() const {
  // @@protoc_insertion_point(field_get:raft.requestVoteArgs.last_log_term)
  return _internal_last_log_term();
}
inline void requestVoteArgs::_internal_set_last_log_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  last_log_term_ = value;
}
inline void requestVoteArgs::set_last_log_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_last_log_term(value);
  // @@protoc_insertion_point(field_set:raft.requestVoteArgs.last_log_term)
}

// -------------------------------------------------------------------

// requestVoteReply

// int32 term = 1;
inline void requestVoteReply::clear_term() {
  term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 requestVoteReply::_internal_term() const {
  return term_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 requestVoteReply::term() const {
  // @@protoc_insertion_point(field_get:raft.requestVoteReply.term)
  return _internal_term();
}
inline void requestVoteReply::_internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  term_ = value;
}
inline void requestVoteReply::set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.requestVoteReply.term)
}

// bool vote_granted = 2;
inline void requestVoteReply::clear_vote_granted() {
  vote_granted_ = false;
}
inline bool requestVoteReply::_internal_vote_granted() const {
  return vote_granted_;
}
inline bool requestVoteReply::vote_granted() const {
  // @@protoc_insertion_point(field_get:raft.requestVoteReply.vote_granted)
  return _internal_vote_granted();
}
inline void requestVoteReply::_internal_set_vote_granted(bool value) {
  
  vote_granted_ = value;
}
inline void requestVoteReply::set_vote_granted(bool value) {
  _internal_set_vote_granted(value);
  // @@protoc_insertion_point(field_set:raft.requestVoteReply.vote_granted)
}

// .raft.voteState state = 3;
inline void requestVoteReply::clear_state() {
  state_ = 0;
}
inline ::raft::voteState requestVoteReply::_internal_state() const {
  return static_cast< ::raft::voteState >(state_);
}
inline ::raft::voteState requestVoteReply::state() const {
  // @@protoc_insertion_point(field_get:raft.requestVoteReply.state)
  return _internal_state();
}
inline void requestVoteReply::_internal_set_state(::raft::voteState value) {
  
  state_ = value;
}
inline void requestVoteReply::set_state(::raft::voteState value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:raft.requestVoteReply.state)
}

// -------------------------------------------------------------------

// installSnapshotArgs

// int32 leader_id = 1;
inline void installSnapshotArgs::clear_leader_id() {
  leader_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 installSnapshotArgs::_internal_leader_id() const {
  return leader_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 installSnapshotArgs::leader_id() const {
  // @@protoc_insertion_point(field_get:raft.installSnapshotArgs.leader_id)
  return _internal_leader_id();
}
inline void installSnapshotArgs::_internal_set_leader_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  leader_id_ = value;
}
inline void installSnapshotArgs::set_leader_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_leader_id(value);
  // @@protoc_insertion_point(field_set:raft.installSnapshotArgs.leader_id)
}

// int32 term = 2;
inline void installSnapshotArgs::clear_term() {
  term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 installSnapshotArgs::_internal_term() const {
  return term_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 installSnapshotArgs::term() const {
  // @@protoc_insertion_point(field_get:raft.installSnapshotArgs.term)
  return _internal_term();
}
inline void installSnapshotArgs::_internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  term_ = value;
}
inline void installSnapshotArgs::set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.installSnapshotArgs.term)
}

// int32 last_index = 3;
inline void installSnapshotArgs::clear_last_index() {
  last_index_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 installSnapshotArgs::_internal_last_index() const {
  return last_index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 installSnapshotArgs::last_index() const {
  // @@protoc_insertion_point(field_get:raft.installSnapshotArgs.last_index)
  return _internal_last_index();
}
inline void installSnapshotArgs::_internal_set_last_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  last_index_ = value;
}
inline void installSnapshotArgs::set_last_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_last_index(value);
  // @@protoc_insertion_point(field_set:raft.installSnapshotArgs.last_index)
}

// int32 last_term = 4;
inline void installSnapshotArgs::clear_last_term() {
  last_term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 installSnapshotArgs::_internal_last_term() const {
  return last_term_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 installSnapshotArgs::last_term() const {
  // @@protoc_insertion_point(field_get:raft.installSnapshotArgs.last_term)
  return _internal_last_term();
}
inline void installSnapshotArgs::_internal_set_last_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  last_term_ = value;
}
inline void installSnapshotArgs::set_last_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_last_term(value);
  // @@protoc_insertion_point(field_set:raft.installSnapshotArgs.last_term)
}

// bytes data = 5;
inline void installSnapshotArgs::clear_data() {
  data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& installSnapshotArgs::data() const {
  // @@protoc_insertion_point(field_get:raft.installSnapshotArgs.data)
  return _internal_data();
}
inline void installSnapshotArgs::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:raft.installSnapshotArgs.data)
}
inline std::string* installSnapshotArgs::mutable_data() {
  // @@protoc_insertion_point(field_mutable:raft.installSnapshotArgs.data)
  return _internal_mutable_data();
}
inline const std::string& installSnapshotArgs::_internal_data() const {
  return data_.Get();
}
inline void installSnapshotArgs::_internal_set_data(const std::string& value) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void installSnapshotArgs::set_data(std::string&& value) {
  
  data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:raft.installSnapshotArgs.data)
}
inline void installSnapshotArgs::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:raft.installSnapshotArgs.data)
}
inline void installSnapshotArgs::set_data(const void* value,
    size_t size) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:raft.installSnapshotArgs.data)
}
inline std::string* installSnapshotArgs::_internal_mutable_data() {
  
  return data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* installSnapshotArgs::release_data() {
  // @@protoc_insertion_point(field_release:raft.installSnapshotArgs.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void installSnapshotArgs::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:raft.installSnapshotArgs.data)
}
inline std::string* installSnapshotArgs::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:raft.installSnapshotArgs.data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void installSnapshotArgs::unsafe_arena_set_allocated_data(
    std::string* data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (data != nullptr) {
    
  } else {
    
  }
  data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:raft.installSnapshotArgs.data)
}

// -------------------------------------------------------------------

// installSnapshotReply

// int32 term = 1;
inline void installSnapshotReply::clear_term() {
  term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 installSnapshotReply::_internal_term() const {
  return term_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 installSnapshotReply::term() const {
  // @@protoc_insertion_point(field_get:raft.installSnapshotReply.term)
  return _internal_term();
}
inline void installSnapshotReply::_internal_set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  term_ = value;
}
inline void installSnapshotReply::set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.installSnapshotReply.term)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace raft

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::raft::netState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::raft::netState>() {
  return ::raft::netState_descriptor();
}
template <> struct is_proto_enum< ::raft::voteState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::raft::voteState>() {
  return ::raft::voteState_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_raftBase_2eproto
